name: CI - Selenium UI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Selenium UI Tests
    runs-on: ubuntu-latest
    container:
      image: openjdk:17-jdk-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install wget and unzip
        run: |
          apt-get update
          apt-get install -y wget unzip

      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip gradle-7.6-bin.zip
          mv gradle-7.6 /opt/gradle
          ln -s /opt/gradle/bin/gradle /usr/bin/gradle

      - name: Run tests with Gradle
        run: |
          gradle clean test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/test
